name: Test PHP Recipes

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-php:
    name: test php recipes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: json, curl, simplexml, spl, pcre
          coverage: xdebug
      - name: Install dependencies
        working-directory: ./code-recipes/php
        run: composer install --prefer-dist --no-progress
      - name: Test with PHPUnit and cleanup
        working-directory: ./code-recipes/php
        run: |
          mkdir -p build/reports
          vendor/bin/phpunit test --testdox --log-junit build/reports/phpunit.xml
      - name: Archive reports
        uses: actions/upload-artifact@v4
        with:
          name: php-test-reports
          path: code-recipes/php/build/reports